name: chat_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  flutter_chat_ui: ^1.5.8
  uuid: ^3.0.6
  open_file: ^3.2.1
  mime: ^1.0.1
  intl: ^0.17.0
  image_picker: ^0.8.5
  file_picker: ^4.5.1

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  
  assets:
    - messages.json
